name = "cynthia_websites_mini_server"
target = "javascript"
gleam = ">= 1.9.0"
version = "1.3.0"

description = "The Cynthia Mini server."
licences = ["AGPL-3.0"]
repository = { type = "github", user = "CynthiaWebsiteEngine", repo = "Mini", path = "cynthia_websites_mini_server" }
links = [
	{ title = "NPM", href = "https://www.npmjs.com/package/@cynthiaweb/cynthiaweb-mini" },
	{ title = "GitHub releases", href = "https://github.com/CynthiaWebsiteEngine/Mini/releases" }
]


[javascript]
runtime = "bun"
typescript_declarations = true

[dependencies]
# Shared dependencies with the client
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
plinth = ">= 0.9.2 and < 1.0.0"
tom = "1.1.1"

# Other dependencies
argv = "1.0.2"
birl = "1.8.0"
bungibindies = "1.2.0-rc"
cynthia_websites_mini_client = { path = "../cynthia_websites_mini_client" }
simplifile = "2.2.1"
gleamy_lights = ">= 2.3.1 and < 3.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.2.7 and < 2.0.0"
pprint = ">= 1.0.5 and < 2.0.0"
