name = "cynthia_websites_mini_client"
target = "javascript"
gleam = ">= 1.9.0"
version = "1.3.0"
description = "The Cynthia Mini client."
licences = ["AGPL-3.0"]
repository = { type = "github", user = "CynthiaWebsiteEngine", repo = "Mini", path = "cynthia_websites_mini_client" }
links = [
	{ title = "NPM", href = "https://www.npmjs.com/package/@cynthiaweb/cynthiaweb-mini" },
	{ title = "GitHub releases", href = "https://github.com/CynthiaWebsiteEngine/Mini/releases" }
]

[javascript]
typescript_declarations = true

[dependencies]
# Shared dependencies with the server
gleam_stdlib = "0.59.0"
plinth = ">= 0.5.9 and < 1.0.0"
gleam_javascript = "1.0.0"
gleam_community_colour = "1.4.1"
gleam_json = "2.3.0"
gleam_http = "3.7.2"
gleam_fetch = "1.3.0"

# Lustre specific dependencies
lustre = ">= 5.0.2 and < 6.0.0"
rsvp = ">= 1.0.0 and < 2.0.0"
modem = "2.0.2"


# Other dependencies
odysseus = ">= 1.0.0 and < 2.0.0"
houdini = ">= 1.1.0 and < 2.0.0"
jot = ">= 5.0.0 and < 6.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"


[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.2.7 and < 2.0.0"
